CREATE PROCEDURE [dbo].pr_AGENTCONFIGURATION_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	AGENTCONFIGURATIONID int,
	NAME varchar(60),
	DESCRIPTION varchar(2048),
	CREATEDATE datetime2,
	ISDEFAULT int,
	ISDELETED int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT AGENTCONFIGURATIONID,NAME,DESCRIPTION,CREATEDATE,ISDEFAULT,ISDELETED FROM AGENTCONFIGURATION_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @AGENTCONFIGURATIONID int,@NAME varchar(60),@DESCRIPTION varchar(2048),@CREATEDATE datetime2,@ISDEFAULT int,@ISDELETED int

DECLARE update_cursor CURSOR FOR 
SELECT AGENTCONFIGURATIONID,NAME,DESCRIPTION,CREATEDATE,ISDEFAULT,ISDELETED FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @AGENTCONFIGURATIONID,@NAME,@DESCRIPTION,@CREATEDATE,@ISDEFAULT,@ISDELETED

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE AGENTCONFIGURATION SET
		NAME=@NAME,
		DESCRIPTION=@DESCRIPTION,
		CREATEDATE=@CREATEDATE,
		ISDEFAULT=@ISDEFAULT,
		ISDELETED=@ISDELETED
	WHERE
		SERVERID = @svrId
	AND AGENTCONFIGURATIONID=@AGENTCONFIGURATIONID

FETCH NEXT FROM update_cursor
INTO @AGENTCONFIGURATIONID,@NAME,@DESCRIPTION,@CREATEDATE,@ISDEFAULT,@ISDELETED

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM AGENTCONFIGURATION_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
