CREATE PROCEDURE [dbo].pr_AGENT_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	AGENTID int,
	AGENTNAME varchar(256),
	AGGREGATORID int,
	VERSION varchar(20),
	STATUS varchar(20),
	ISDELETED int,
	AGENTIPADDRESS varchar(32),
	CONNECTSTATUS varchar(20),
	AGENTCONFIGURATIONVERSIONID int,
	INVESTIGATING int,
	LASTCONNECTIONTIME datetime2
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT AGENTID,AGENTNAME,AGGREGATORID,VERSION,STATUS,ISDELETED,AGENTIPADDRESS,CONNECTSTATUS,AGENTCONFIGURATIONVERSIONID,INVESTIGATING,LASTCONNECTIONTIME FROM AGENT_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @AGENTID int,@AGENTNAME varchar(256),@AGGREGATORID int,@VERSION varchar(20),@STATUS varchar(20),@ISDELETED int,@AGENTIPADDRESS varchar(32),@CONNECTSTATUS varchar(20),@AGENTCONFIGURATIONVERSIONID int,@INVESTIGATING int,@LASTCONNECTIONTIME datetime2

DECLARE update_cursor CURSOR FOR 
SELECT AGENTID,AGENTNAME,AGGREGATORID,VERSION,STATUS,ISDELETED,AGENTIPADDRESS,CONNECTSTATUS,AGENTCONFIGURATIONVERSIONID,INVESTIGATING,LASTCONNECTIONTIME FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @AGENTID,@AGENTNAME,@AGGREGATORID,@VERSION,@STATUS,@ISDELETED,@AGENTIPADDRESS,@CONNECTSTATUS,@AGENTCONFIGURATIONVERSIONID,@INVESTIGATING,@LASTCONNECTIONTIME

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE AGENT SET
		AGENTNAME=@AGENTNAME,
		AGGREGATORID=@AGGREGATORID,
		VERSION=@VERSION,
		STATUS=@STATUS,
		ISDELETED=@ISDELETED,
		AGENTIPADDRESS=@AGENTIPADDRESS,
		CONNECTSTATUS=@CONNECTSTATUS,
		AGENTCONFIGURATIONVERSIONID=@AGENTCONFIGURATIONVERSIONID,
		INVESTIGATING=@INVESTIGATING,
		LASTCONNECTIONTIME=@LASTCONNECTIONTIME
	WHERE
		SERVERID = @svrId
	AND AGENTID=@AGENTID

FETCH NEXT FROM update_cursor
INTO @AGENTID,@AGENTNAME,@AGGREGATORID,@VERSION,@STATUS,@ISDELETED,@AGENTIPADDRESS,@CONNECTSTATUS,@AGENTCONFIGURATIONVERSIONID,@INVESTIGATING,@LASTCONNECTIONTIME

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM AGENT_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
