CREATE PROCEDURE [dbo].pr_AGENTCONFIGURATIONVERSION_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	AGENTCONFIGURATIONVERSIONID int,
	AGENTCONFIGURATIONID int,
	VERSION int,
	PROTOCOLFILTERID int,
	MODIFYDATE datetime2,
	ISLATEST int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT AGENTCONFIGURATIONVERSIONID,AGENTCONFIGURATIONID,VERSION,PROTOCOLFILTERID,MODIFYDATE,ISLATEST FROM AGENTCONFIGURATIONVERSION_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @AGENTCONFIGURATIONVERSIONID int,@AGENTCONFIGURATIONID int,@VERSION int,@PROTOCOLFILTERID int,@MODIFYDATE datetime2,@ISLATEST int

DECLARE update_cursor CURSOR FOR 
SELECT AGENTCONFIGURATIONVERSIONID,AGENTCONFIGURATIONID,VERSION,PROTOCOLFILTERID,MODIFYDATE,ISLATEST FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @AGENTCONFIGURATIONVERSIONID,@AGENTCONFIGURATIONID,@VERSION,@PROTOCOLFILTERID,@MODIFYDATE,@ISLATEST

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE AGENTCONFIGURATIONVERSION SET
		AGENTCONFIGURATIONID=@AGENTCONFIGURATIONID,
		VERSION=@VERSION,
		PROTOCOLFILTERID=@PROTOCOLFILTERID,
		MODIFYDATE=@MODIFYDATE,
		ISLATEST=@ISLATEST
	WHERE
		SERVERID = @svrId
	AND AGENTCONFIGURATIONVERSIONID=@AGENTCONFIGURATIONVERSIONID

FETCH NEXT FROM update_cursor
INTO @AGENTCONFIGURATIONVERSIONID,@AGENTCONFIGURATIONID,@VERSION,@PROTOCOLFILTERID,@MODIFYDATE,@ISLATEST

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM AGENTCONFIGURATIONVERSION_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
