CREATE PROCEDURE [dbo].pr_CONTENTROOT_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	CONTENTROOTID int,
	COURSEID int,
	URI varchar(1024),
	MAXDEPTH int,
	USERNAME varchar(256),
	REMEDIATIONUSERNAME varchar(256),
	ISDELETED int,
	CONTENTROOTDATAID int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT CONTENTROOTID,COURSEID,URI,MAXDEPTH,USERNAME,REMEDIATIONUSERNAME,ISDELETED,CONTENTROOTDATAID FROM CONTENTROOT_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @CONTENTROOTID int,@COURSEID int,@URI varchar(1024),@MAXDEPTH int,@USERNAME varchar(256),@REMEDIATIONUSERNAME varchar(256),@ISDELETED int,@CONTENTROOTDATAID int

DECLARE update_cursor CURSOR FOR 
SELECT CONTENTROOTID,COURSEID,URI,MAXDEPTH,USERNAME,REMEDIATIONUSERNAME,ISDELETED,CONTENTROOTDATAID FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @CONTENTROOTID,@COURSEID,@URI,@MAXDEPTH,@USERNAME,@REMEDIATIONUSERNAME,@ISDELETED,@CONTENTROOTDATAID

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE CONTENTROOT SET
		COURSEID=@COURSEID,
		URI=@URI,
		MAXDEPTH=@MAXDEPTH,
		USERNAME=@USERNAME,
		REMEDIATIONUSERNAME=@REMEDIATIONUSERNAME,
		ISDELETED=@ISDELETED,
		CONTENTROOTDATAID=@CONTENTROOTDATAID
	WHERE
		SERVERID = @svrId
	AND CONTENTROOTID=@CONTENTROOTID

FETCH NEXT FROM update_cursor
INTO @CONTENTROOTID,@COURSEID,@URI,@MAXDEPTH,@USERNAME,@REMEDIATIONUSERNAME,@ISDELETED,@CONTENTROOTDATAID

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM CONTENTROOT_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
