CREATE PROCEDURE [dbo].pr_COURSE_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	COURSEID int,
	FILENAMEPATTERNFILTER varchar(1024),
	FILENAMEPATTERNEXCLUDEFILTER varchar(1024),
	MINFILESIZEFILTER int,
	MAXFILESIZEFILTER int,
	MINFILEMODIFICATIONDATEFILTER datetime2,
	MAXFILEMODIFICATIONDATEFILTER datetime2,
	MINFILELASTACCESSEDDATEFILTER datetime2,
	MAXFILELASTACCESSEDDATEFILTER datetime2,
	DEFAULTUSERNAME varchar(256),
	ISDELETED int,
	ISDIFFERENTIAL int,
	MARKNEXTSCANFULL int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT COURSEID,FILENAMEPATTERNFILTER,FILENAMEPATTERNEXCLUDEFILTER,MINFILESIZEFILTER,MAXFILESIZEFILTER,MINFILEMODIFICATIONDATEFILTER,MAXFILEMODIFICATIONDATEFILTER,MINFILELASTACCESSEDDATEFILTER,MAXFILELASTACCESSEDDATEFILTER,DEFAULTUSERNAME,ISDELETED,ISDIFFERENTIAL,MARKNEXTSCANFULL FROM COURSE_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @COURSEID int,@FILENAMEPATTERNFILTER varchar(1024),@FILENAMEPATTERNEXCLUDEFILTER varchar(1024),@MINFILESIZEFILTER int,@MAXFILESIZEFILTER int,@MINFILEMODIFICATIONDATEFILTER datetime2,@MAXFILEMODIFICATIONDATEFILTER datetime2,@MINFILELASTACCESSEDDATEFILTER datetime2,@MAXFILELASTACCESSEDDATEFILTER datetime2,@DEFAULTUSERNAME varchar(256),@ISDELETED int,@ISDIFFERENTIAL int,@MARKNEXTSCANFULL int

DECLARE update_cursor CURSOR FOR 
SELECT COURSEID,FILENAMEPATTERNFILTER,FILENAMEPATTERNEXCLUDEFILTER,MINFILESIZEFILTER,MAXFILESIZEFILTER,MINFILEMODIFICATIONDATEFILTER,MAXFILEMODIFICATIONDATEFILTER,MINFILELASTACCESSEDDATEFILTER,MAXFILELASTACCESSEDDATEFILTER,DEFAULTUSERNAME,ISDELETED,ISDIFFERENTIAL,MARKNEXTSCANFULL FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @COURSEID,@FILENAMEPATTERNFILTER,@FILENAMEPATTERNEXCLUDEFILTER,@MINFILESIZEFILTER,@MAXFILESIZEFILTER,@MINFILEMODIFICATIONDATEFILTER,@MAXFILEMODIFICATIONDATEFILTER,@MINFILELASTACCESSEDDATEFILTER,@MAXFILELASTACCESSEDDATEFILTER,@DEFAULTUSERNAME,@ISDELETED,@ISDIFFERENTIAL,@MARKNEXTSCANFULL

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE COURSE SET
		FILENAMEPATTERNFILTER=@FILENAMEPATTERNFILTER,
		FILENAMEPATTERNEXCLUDEFILTER=@FILENAMEPATTERNEXCLUDEFILTER,
		MINFILESIZEFILTER=@MINFILESIZEFILTER,
		MAXFILESIZEFILTER=@MAXFILESIZEFILTER,
		MINFILEMODIFICATIONDATEFILTER=@MINFILEMODIFICATIONDATEFILTER,
		MAXFILEMODIFICATIONDATEFILTER=@MAXFILEMODIFICATIONDATEFILTER,
		MINFILELASTACCESSEDDATEFILTER=@MINFILELASTACCESSEDDATEFILTER,
		MAXFILELASTACCESSEDDATEFILTER=@MAXFILELASTACCESSEDDATEFILTER,
		DEFAULTUSERNAME=@DEFAULTUSERNAME,
		ISDELETED=@ISDELETED,
		ISDIFFERENTIAL=@ISDIFFERENTIAL,
		MARKNEXTSCANFULL=@MARKNEXTSCANFULL
	WHERE
		SERVERID = @svrId
	AND COURSEID=@COURSEID

FETCH NEXT FROM update_cursor
INTO @COURSEID,@FILENAMEPATTERNFILTER,@FILENAMEPATTERNEXCLUDEFILTER,@MINFILESIZEFILTER,@MAXFILESIZEFILTER,@MINFILEMODIFICATIONDATEFILTER,@MAXFILEMODIFICATIONDATEFILTER,@MINFILELASTACCESSEDDATEFILTER,@MAXFILELASTACCESSEDDATEFILTER,@DEFAULTUSERNAME,@ISDELETED,@ISDIFFERENTIAL,@MARKNEXTSCANFULL

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM COURSE_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
