CREATE PROCEDURE [dbo].pr_CUSTOMATTRIBUTEGROUP_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	CUSTOMATTRIBUTEGROUPID int,
	NAME nvarchar(120),
	ISINTERNATIONALIZED int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT CUSTOMATTRIBUTEGROUPID,NAME,ISINTERNATIONALIZED FROM CUSTOMATTRIBUTEGROUP_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @CUSTOMATTRIBUTEGROUPID int,@NAME nvarchar(120),@ISINTERNATIONALIZED int

DECLARE update_cursor CURSOR FOR 
SELECT CUSTOMATTRIBUTEGROUPID,NAME,ISINTERNATIONALIZED FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @CUSTOMATTRIBUTEGROUPID,@NAME,@ISINTERNATIONALIZED

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE CUSTOMATTRIBUTEGROUP SET
		NAME=@NAME,
		ISINTERNATIONALIZED=@ISINTERNATIONALIZED
	WHERE
		SERVERID = @svrId
	AND CUSTOMATTRIBUTEGROUPID=@CUSTOMATTRIBUTEGROUPID

FETCH NEXT FROM update_cursor
INTO @CUSTOMATTRIBUTEGROUPID,@NAME,@ISINTERNATIONALIZED

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM CUSTOMATTRIBUTEGROUP_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
