CREATE PROCEDURE [dbo].pr_CUSTOMATTRIBUTEDEFINITION_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	CUSTOMATTRIBUTEDEFINITIONID int,
	NAME nvarchar(60),
	COLUMNINDEX int,
	DISPLAYORDER int,
	ISEMAILADDRESS int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT CUSTOMATTRIBUTEDEFINITIONID,NAME,COLUMNINDEX,DISPLAYORDER,ISEMAILADDRESS FROM CUSTOMATTRIBUTEDEFINITION_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @CUSTOMATTRIBUTEDEFINITIONID int,@NAME nvarchar(60),@COLUMNINDEX int,@DISPLAYORDER int,@ISEMAILADDRESS int

DECLARE update_cursor CURSOR FOR 
SELECT CUSTOMATTRIBUTEDEFINITIONID,NAME,COLUMNINDEX,DISPLAYORDER,ISEMAILADDRESS FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @CUSTOMATTRIBUTEDEFINITIONID,@NAME,@COLUMNINDEX,@DISPLAYORDER,@ISEMAILADDRESS

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE CUSTOMATTRIBUTEDEFINITION SET
		NAME=@NAME,
		COLUMNINDEX=@COLUMNINDEX,
		DISPLAYORDER=@DISPLAYORDER,
		ISEMAILADDRESS=@ISEMAILADDRESS
	WHERE
		SERVERID = @svrId
	AND CUSTOMATTRIBUTEDEFINITIONID=@CUSTOMATTRIBUTEDEFINITIONID

FETCH NEXT FROM update_cursor
INTO @CUSTOMATTRIBUTEDEFINITIONID,@NAME,@COLUMNINDEX,@DISPLAYORDER,@ISEMAILADDRESS

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM CUSTOMATTRIBUTEDEFINITION_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
