CREATE PROCEDURE [dbo].pr_INCIDENT_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	INCIDENTID int,
	MESSAGEID int,
	POLICYID int,
	POLICYVERSION int,
	INCIDENTSTATUSID int,
	VIOLATIONCOUNT int,
	DETECTIONDATE datetime2,
	POLICYGROUPID int,
	CUSTOMATTRIBUTESRECORDID int,
	ISDELETED int,
	BLOCKEDSTATUS int,
	INCIDENTSEVERITYID int,
	MESSAGETYPE int,
	DISCOVERITEMID int,
	DISCOVERMILLISSINCEFIRSTSEEN numeric,
	CREATIONDATE datetime2,
	DATAOWNERID int,
	DATAOWNEREMAILID int,
	ISBLOCKEDSTATUSSUPERSEDED int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT INCIDENTID,MESSAGEID,POLICYID,POLICYVERSION,INCIDENTSTATUSID,VIOLATIONCOUNT,DETECTIONDATE,POLICYGROUPID,CUSTOMATTRIBUTESRECORDID,ISDELETED,BLOCKEDSTATUS,INCIDENTSEVERITYID,MESSAGETYPE,DISCOVERITEMID,DISCOVERMILLISSINCEFIRSTSEEN,CREATIONDATE,DATAOWNERID,DATAOWNEREMAILID,ISBLOCKEDSTATUSSUPERSEDED FROM INCIDENT_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @INCIDENTID int,@MESSAGEID int,@POLICYID int,@POLICYVERSION int,@INCIDENTSTATUSID int,@VIOLATIONCOUNT int,@DETECTIONDATE datetime2,@POLICYGROUPID int,@CUSTOMATTRIBUTESRECORDID int,@ISDELETED int,@BLOCKEDSTATUS int,@INCIDENTSEVERITYID int,@MESSAGETYPE int,@DISCOVERITEMID int,@DISCOVERMILLISSINCEFIRSTSEEN numeric,@CREATIONDATE datetime2,@DATAOWNERID int,@DATAOWNEREMAILID int,@ISBLOCKEDSTATUSSUPERSEDED int

DECLARE update_cursor CURSOR FOR 
SELECT INCIDENTID,MESSAGEID,POLICYID,POLICYVERSION,INCIDENTSTATUSID,VIOLATIONCOUNT,DETECTIONDATE,POLICYGROUPID,CUSTOMATTRIBUTESRECORDID,ISDELETED,BLOCKEDSTATUS,INCIDENTSEVERITYID,MESSAGETYPE,DISCOVERITEMID,DISCOVERMILLISSINCEFIRSTSEEN,CREATIONDATE,DATAOWNERID,DATAOWNEREMAILID,ISBLOCKEDSTATUSSUPERSEDED FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @INCIDENTID,@MESSAGEID,@POLICYID,@POLICYVERSION,@INCIDENTSTATUSID,@VIOLATIONCOUNT,@DETECTIONDATE,@POLICYGROUPID,@CUSTOMATTRIBUTESRECORDID,@ISDELETED,@BLOCKEDSTATUS,@INCIDENTSEVERITYID,@MESSAGETYPE,@DISCOVERITEMID,@DISCOVERMILLISSINCEFIRSTSEEN,@CREATIONDATE,@DATAOWNERID,@DATAOWNEREMAILID,@ISBLOCKEDSTATUSSUPERSEDED

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE INCIDENT SET
		MESSAGEID=@MESSAGEID,
		POLICYID=@POLICYID,
		POLICYVERSION=@POLICYVERSION,
		INCIDENTSTATUSID=@INCIDENTSTATUSID,
		VIOLATIONCOUNT=@VIOLATIONCOUNT,
		DETECTIONDATE=@DETECTIONDATE,
		POLICYGROUPID=@POLICYGROUPID,
		CUSTOMATTRIBUTESRECORDID=@CUSTOMATTRIBUTESRECORDID,
		ISDELETED=@ISDELETED,
		BLOCKEDSTATUS=@BLOCKEDSTATUS,
		INCIDENTSEVERITYID=@INCIDENTSEVERITYID,
		MESSAGETYPE=@MESSAGETYPE,
		DISCOVERITEMID=@DISCOVERITEMID,
		DISCOVERMILLISSINCEFIRSTSEEN=@DISCOVERMILLISSINCEFIRSTSEEN,
		DATAOWNERID=@DATAOWNERID,
		DATAOWNEREMAILID=@DATAOWNEREMAILID,
		ISBLOCKEDSTATUSSUPERSEDED=@ISBLOCKEDSTATUSSUPERSEDED
	WHERE
		SERVERID = @svrId
	AND INCIDENTID=@INCIDENTID
	AND CREATIONDATE=@CREATIONDATE

FETCH NEXT FROM update_cursor
INTO @INCIDENTID,@MESSAGEID,@POLICYID,@POLICYVERSION,@INCIDENTSTATUSID,@VIOLATIONCOUNT,@DETECTIONDATE,@POLICYGROUPID,@CUSTOMATTRIBUTESRECORDID,@ISDELETED,@BLOCKEDSTATUS,@INCIDENTSEVERITYID,@MESSAGETYPE,@DISCOVERITEMID,@DISCOVERMILLISSINCEFIRSTSEEN,@CREATIONDATE,@DATAOWNERID,@DATAOWNEREMAILID,@ISBLOCKEDSTATUSSUPERSEDED

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM INCIDENT_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
