CREATE PROCEDURE [dbo].pr_INCIDENTSTATUS_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	INCIDENTSTATUSID int,
	NAME varchar(100),
	MENUORDER int,
	ISDEFAULT int,
	ISDELETED int,
	ISINTERNATIONALIZED int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT INCIDENTSTATUSID,NAME,MENUORDER,ISDEFAULT,ISDELETED,ISINTERNATIONALIZED FROM INCIDENTSTATUS_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @INCIDENTSTATUSID int,@NAME varchar(100),@MENUORDER int,@ISDEFAULT int,@ISDELETED int,@ISINTERNATIONALIZED int

DECLARE update_cursor CURSOR FOR 
SELECT INCIDENTSTATUSID,NAME,MENUORDER,ISDEFAULT,ISDELETED,ISINTERNATIONALIZED FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @INCIDENTSTATUSID,@NAME,@MENUORDER,@ISDEFAULT,@ISDELETED,@ISINTERNATIONALIZED

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE INCIDENTSTATUS SET
		NAME=@NAME,
		MENUORDER=@MENUORDER,
		ISDEFAULT=@ISDEFAULT,
		ISDELETED=@ISDELETED,
		ISINTERNATIONALIZED=@ISINTERNATIONALIZED
	WHERE
		SERVERID = @svrId
	AND INCIDENTSTATUSID=@INCIDENTSTATUSID

FETCH NEXT FROM update_cursor
INTO @INCIDENTSTATUSID,@NAME,@MENUORDER,@ISDEFAULT,@ISDELETED,@ISINTERNATIONALIZED

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM INCIDENTSTATUS_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
