CREATE PROCEDURE [dbo].pr_POLICYGROUP_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	POLICYGROUPID int,
	NAME nvarchar(120),
	DESCRIPTION varchar(2048),
	EDITDATE datetime2,
	ISDELETED int,
	ISINTERNATIONALIZED int,
	ALLMONITORSFLAG int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT POLICYGROUPID,NAME,DESCRIPTION,EDITDATE,ISDELETED,ISINTERNATIONALIZED,ALLMONITORSFLAG FROM POLICYGROUP_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @POLICYGROUPID int,@NAME nvarchar(120),@DESCRIPTION varchar(2048),@EDITDATE datetime2,@ISDELETED int,@ISINTERNATIONALIZED int,@ALLMONITORSFLAG int

DECLARE update_cursor CURSOR FOR 
SELECT POLICYGROUPID,NAME,DESCRIPTION,EDITDATE,ISDELETED,ISINTERNATIONALIZED,ALLMONITORSFLAG FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @POLICYGROUPID,@NAME,@DESCRIPTION,@EDITDATE,@ISDELETED,@ISINTERNATIONALIZED,@ALLMONITORSFLAG

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE POLICYGROUP SET
		NAME=@NAME,
		DESCRIPTION=@DESCRIPTION,
		EDITDATE=@EDITDATE,
		ISDELETED=@ISDELETED,
		ISINTERNATIONALIZED=@ISINTERNATIONALIZED,
		ALLMONITORSFLAG=@ALLMONITORSFLAG
	WHERE
		SERVERID = @svrId
	AND POLICYGROUPID=@POLICYGROUPID

FETCH NEXT FROM update_cursor
INTO @POLICYGROUPID,@NAME,@DESCRIPTION,@EDITDATE,@ISDELETED,@ISINTERNATIONALIZED,@ALLMONITORSFLAG

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM POLICYGROUP_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
