CREATE PROCEDURE [dbo].pr_POLICY_Sync (
@svrName varchar(200),
@svrId int
)
AS
BEGIN
DECLARE @tmpTab TABLE( 
	POLICYID int,
	VERSION int,
	NAME nvarchar(120),
	DESCRIPTION nvarchar(4000),
	ACTIVESTATUS int,
	CREATEDATE datetime2,
	EDITDATE datetime2,
	ISDELETED int,
	ROOTCONDITIONID int,
	POLICYGROUPID int
)

DECLARE @insSQL varchar(MAX)= 'SELECT * FROM '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT POLICYID,VERSION,NAME,DESCRIPTION,ACTIVESTATUS,CREATEDATE,EDITDATE,ISDELETED,ROOTCONDITIONID,POLICYGROUPID FROM POLICY_LOG WHERE ROWNUM<100 ORDER BY LOGTIME')
INSERT INTO @tmpTab EXEC(@insSQL)

DECLARE @POLICYID int,@VERSION int,@NAME nvarchar(120),@DESCRIPTION nvarchar(4000),@ACTIVESTATUS int,@CREATEDATE datetime2,@EDITDATE datetime2,@ISDELETED int,@ROOTCONDITIONID int,@POLICYGROUPID int

DECLARE update_cursor CURSOR FOR 
SELECT POLICYID,VERSION,NAME,DESCRIPTION,ACTIVESTATUS,CREATEDATE,EDITDATE,ISDELETED,ROOTCONDITIONID,POLICYGROUPID FROM @tmpTab

OPEN update_cursor

FETCH NEXT FROM update_cursor
INTO @POLICYID,@VERSION,@NAME,@DESCRIPTION,@ACTIVESTATUS,@CREATEDATE,@EDITDATE,@ISDELETED,@ROOTCONDITIONID,@POLICYGROUPID

WHILE @@FETCH_STATUS = 0
BEGIN	
	UPDATE POLICY SET
		VERSION=@VERSION,
		NAME=@NAME,
		DESCRIPTION=@DESCRIPTION,
		ACTIVESTATUS=@ACTIVESTATUS,
		CREATEDATE=@CREATEDATE,
		EDITDATE=@EDITDATE,
		ISDELETED=@ISDELETED,
		ROOTCONDITIONID=@ROOTCONDITIONID,
		POLICYGROUPID=@POLICYGROUPID
	WHERE
		SERVERID = @svrId
	AND POLICYID=@POLICYID

FETCH NEXT FROM update_cursor
INTO @POLICYID,@VERSION,@NAME,@DESCRIPTION,@ACTIVESTATUS,@CREATEDATE,@EDITDATE,@ISDELETED,@ROOTCONDITIONID,@POLICYGROUPID

END

DECLARE @delSQL varchar(MAX) = 'DELETE '+ dbo.GET_OPENQUERY_SQL(@svrName,'SELECT * FROM POLICY_LOG WHERE ROWNUM < 100')
EXEC(@delSQL)

CLOSE update_cursor
DEALLOCATE update_cursor

END
