/* Formatted on 8/23/2012 1:50:19 PM (QP5 v5.215.12089.38647) */
CREATE TABLE PROTECT.AGENTCONFIGURATION_LOG
AS
   SELECT *
     FROM PROTECT.AGENTCONFIGURATION
    WHERE 1 = 2;

ALTER TABLE PROTECT.AGENTCONFIGURATION_LOG ADD (LOGTIME TIMESTAMP(6));

CREATE OR REPLACE TRIGGER PROTECT.AGENTCONFIGURATION_UPDATE
   AFTER UPDATE OF ISDELETED
   ON PROTECT.AGENTCONFIGURATION
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO PROTECT.AGENTCONFIGURATION_LOG
      (SELECT :NEW.AGENTCONFIGURATIONID,
              :NEW.NAME,
              :NEW.DESCRIPTION,
              :NEW.CREATEDATE,
              :NEW.CREATEUSERID,
              :NEW.ISDEFAULT,
              :NEW.ISDELETED,
              CURRENT_TIMESTAMP
         FROM DUAL);
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END AGENTCONFIGURATION_UPDATE;