/* Formatted on 8/23/2012 1:50:31 PM (QP5 v5.215.12089.38647) */
CREATE TABLE PROTECT.AGENTCONFIGURATIONVERSION_LOG
AS
   SELECT *
     FROM PROTECT.AGENTCONFIGURATIONVERSION
    WHERE 1 = 2;

ALTER TABLE PROTECT.AGENTCONFIGURATIONVERSION_LOG ADD (LOGTIME TIMESTAMP(6));

CREATE OR REPLACE TRIGGER PROTECT.AGENTCONFIGVERSION_UPDATE
   AFTER UPDATE OF ISLATEST
   ON PROTECT.AGENTCONFIGURATIONVERSION
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO PROTECT.AGENTCONFIGURATIONVERSION_LOG
      (SELECT :NEW.AGENTCONFIGURATIONVERSIONID,
              :NEW.AGENTCONFIGURATIONID,
              :NEW.VERSION,
              :NEW.PROTOCOLFILTERID,
              :NEW.MODIFYDATE,
              :NEW.MODIFYUSERID,
              :NEW.ISLATEST,
              CURRENT_TIMESTAMP
         FROM DUAL);
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END AGENTCONFIGVERSION_UPDATE;