/* Formatted on 8/23/2012 1:50:06 PM (QP5 v5.215.12089.38647) */
CREATE TABLE PROTECT.AGENT_LOG
AS
   SELECT *
     FROM PROTECT.AGENT
    WHERE 1 = 2;

ALTER TABLE PROTECT.AGENT_LOG ADD (LOGTIME TIMESTAMP(6));

CREATE OR REPLACE TRIGGER PROTECT.AGENT_UPDATE
   AFTER UPDATE OF STATUS, ISDELETED, CONNECTSTATUS
   ON PROTECT.AGENT
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO PROTECT.AGENT_LOG
      (SELECT :NEW.AGENTID,
              :NEW.AGENTNAME,
              :NEW.AGGREGATORID,
              :NEW.VERSION,
              :NEW.STATUS,
              :NEW.ISDELETED,
              :NEW.AGENTIPADDRESS,
              :NEW.CONNECTSTATUS,
              :NEW.AGENTCONFIGURATIONVERSIONID,
              :NEW.INVESTIGATING,
              :NEW.LASTCONNECTIONTIME,
              CURRENT_TIMESTAMP
         FROM DUAL);
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END AGENT_UPDATE;