/* Formatted on 8/23/2012 1:50:40 PM (QP5 v5.215.12089.38647) */
CREATE TABLE PROTECT.AGENTEVENT_LOG
AS
   SELECT *
     FROM PROTECT.AGENTEVENT
    WHERE 1 = 2;

ALTER TABLE PROTECT.AGENTEVENT_LOG ADD (LOGTIME TIMESTAMP(6));

CREATE OR REPLACE TRIGGER PROTECT.AGENTEVENT_UPDATE
   AFTER UPDATE OF ISDELETED, ISLATEST
   ON PROTECT.AGENTEVENT
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO PROTECT.AGENTEVENT_LOG
      (SELECT :NEW.AGENTEVENTID,
              :NEW.AGENTID,
              :NEW.EVENTDATE,
              :NEW.CATEGORYSTATUSID,
              :NEW.EXTENDEDVALUE,
              :NEW.ISDELETED,
              :NEW.ISLATEST,
              CURRENT_TIMESTAMP
         FROM DUAL);
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END AGENTEVENT_UPDATE;