/* Formatted on 8/23/2012 1:51:59 PM (QP5 v5.215.12089.38647) */
CREATE TABLE PROTECT.CUSTOMATTRIBUTEGROUPMAP_LOG
AS
   SELECT *
     FROM PROTECT.CUSTOMATTRIBUTEGROUPMAP
    WHERE 1 = 2;

ALTER TABLE PROTECT.CUSTOMATTRIBUTEGROUPMAP_LOG ADD (LOGTIME TIMESTAMP(6));

CREATE OR REPLACE TRIGGER PROTECT.CUSTOMATTRIBUTEGROUPMAP_UPDATE
   AFTER UPDATE OF CUSTOMATTRIBUTEGROUPID, CUSTOMATTRIBUTEDEFINITIONID
   ON PROTECT.CUSTOMATTRIBUTEGROUPMAP
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO PROTECT.CUSTOMATTRIBUTEGROUPMAP_LOG
      (SELECT :NEW.CUSTOMATTRIBUTEGROUPID,
              :NEW.CUSTOMATTRIBUTEDEFINITIONID,
              CURRENT_TIMESTAMP
         FROM DUAL);
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END CUSTOMATTRIBUTEGROUPMAP_UPDATE;