/* Formatted on 8/23/2012 1:58:48 PM (QP5 v5.215.12089.38647) */
CREATE TABLE PROTECT.POLICYGROUP_LOG
AS
   SELECT *
     FROM PROTECT.POLICYGROUP
    WHERE 1 = 2;

ALTER TABLE PROTECT.POLICYGROUP_LOG ADD (LOGTIME TIMESTAMP(6));

CREATE OR REPLACE TRIGGER PROTECT.POLICYGROUP_UPDATE
   AFTER UPDATE OF NAME, DESCRIPTION, ISDELETED, ISINTERNATIONALIZED, ALLMONITORSFLAG
   ON PROTECT.POLICYGROUP
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   INSERT INTO PROTECT.POLICYGROUP_LOG
      (SELECT :NEW.POLICYGROUPID,
              :NEW.NAME,
              :NEW.DESCRIPTION,
              :NEW.EDITUSERID,
              :NEW.EDITDATE,
              :NEW.ISDELETED,
              :NEW.ISINTERNATIONALIZED,
              :NEW.ALLMONITORSFLAG,
              CURRENT_TIMESTAMP
         FROM DUAL);
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END POLICYGROUP_UPDATE;